### ISSUE TITLE
Are csscompilation and jscompilation required fields for a proper bundle registration?

### ISSUE THREAD

**Issue by timitos** [collective/mockup-minimalpattern#1]
It is not clear if the fields csscompilation and jscompilation are required fields if a bundle is registered.

If the fields are missing the execution of plone-compile-resources will fail with a traceback.

**Comment by simahawk** [comment]
It looks like that, since in the theming training at ploneconf we ended up w/ a broken script because we registered a bundle w/ no JS.

**Comment by jensens** [comment]
merged fixes by @petschki and @timitos
